version: '2'
services:
  app:
    image: docker-app
    expose:
        - "8080"
    ports:
     - "8080:8080"
    volumes:
     - ~/Projects/docker-workshop/app:/app
    links:
     - mongo
  mongo:
    image: mongo
